[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["cd apps/api && pnpm run build"]

[start]
cmd = "cd apps/api && node dist/main"

[variables]
NODE_ENV = "production"
